// src/context/actionTypes.js
export const FETCH_LIBRARIES_REQUEST = 'FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'FETCH_LIBRARIES_FAILURE';
export const FETCH_LIBRARY_BOOKS_REQUEST = 'FETCH_LIBRARY_BOOKS_REQUEST';
export const FETCH_LIBRARY_BOOKS_SUCCESS = 'FETCH_LIBRARY_BOOKS_SUCCESS';
export const FETCH_LIBRARY_BOOKS_FAILURE = 'FETCH_LIBRARY_BOOKS_FAILURE';

export const ADD_LIBRARY_BOOK_REQUEST = 'ADD_LIBRARY_BOOK_REQUEST';
export const ADD_LIBRARY_BOOK_SUCCESS = 'ADD_LIBRARY_BOOK_SUCCESS';
export const ADD_LIBRARY_BOOK_FAILURE = 'ADD_LIBRARY_BOOK_FAILURE';

export const UPDATE_LIBRARY_BOOK_REQUEST = 'UPDATE_LIBRARY_BOOK_REQUEST';
export const UPDATE_LIBRARY_BOOK_SUCCESS = 'UPDATE_LIBRARY_BOOK_SUCCESS';
export const UPDATE_LIBRARY_BOOK_FAILURE = 'UPDATE_LIBRARY_BOOK_FAILURE';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER_HISTORY_START = 'FETCH_USER_HISTORY_START';
export const FETCH_USER_HISTORY_SUCCESS = 'FETCH_USER_HISTORY_SUCCESS';
export const FETCH_USER_HISTORY_ERROR = 'FETCH_USER_HISTORY_ERROR';



export const CHECKOUT_LIBRARY_BOOK_REQUEST = 'CHECKOUT_LIBRARY_BOOK_REQUEST';
export const CHECKOUT_LIBRARY_BOOK_SUCCESS = 'CHECKOUT_LIBRARY_BOOK_SUCCESS';
export const CHECKOUT_LIBRARY_BOOK_FAILURE = 'CHECKOUT_LIBRARY_BOOK_FAILURE';

export const CHECKIN_LIBRARY_BOOK_REQUEST = 'CHECKIN_LIBRARY_BOOK_REQUEST';
export const CHECKIN_LIBRARY_BOOK_SUCCESS = 'CHECKIN_LIBRARY_BOOK_SUCCESS';
export const CHECKIN_LIBRARY_BOOK_FAILURE = 'CHECKIN_LIBRARY_BOOK_FAILURE';


// TYPEAHEAD
export const FETCH_TYPEAHEAD_REQUEST = 'FETCH_TYPEAHEAD_REQUEST';
export const FETCH_TYPEAHEAD_SUCCESS = 'FETCH_TYPEAHEAD_SUCCESS';
export const FETCH_TYPEAHEAD_FAILURE = 'FETCH_TYPEAHEAD_FAILURE';
export const CLEAR_TYPEAHEAD = 'CLEAR_TYPEAHEAD';

