// src/context/actionTypes.js
export const FETCH_LIBRARIES_REQUEST = 'FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'FETCH_LIBRARIES_FAILURE';
export const FETCH_LIBRARY_BOOKS_REQUEST = 'FETCH_LIBRARY_BOOKS_REQUEST';
export const FETCH_LIBRARY_BOOKS_SUCCESS = 'FETCH_LIBRARY_BOOKS_SUCCESS';
export const FETCH_LIBRARY_BOOKS_FAILURE = 'FETCH_LIBRARY_BOOKS_FAILURE';
